### PR TITLE
Remove everything

### LINKED ISSUE #5: Any plans on adding week 1 2 3 5 6?
yeah

### PR DESCRIPTION
**Pull request by PrincessMtH**
Fixes #5

### CODE REVIEW

**Comment by cuckydev** [comment]
I love it! Pulling right now.

**Comment by CyndaquilDAC** [comment]
I’m assuming mth isnt a fan of this considering it includes week 7

**Comment by PrincessMtH** [comment]
i hate week 7 please remove it

**Comment by cuckydev** [comment]
ok

**Pull request closed without merging**
